import Head from 'next/head'
import * as React from 'react';
import Typography from '@mui/material/Typography';
import Box from '@mui/material/Box';
import Chip from '@mui/material/Chip';
import Stack from '@mui/material/Stack';
import Paper from '@mui/material/Paper';

const query = ` 
query($slug: String!) {
    experienceCollection(where: { slug: $slug }) {
      items {
        order
        slug
        name
        position
        location
        dateRange
        url
        linkedin
        experience {
          json
        }
        skillsCollection(limit:10) {
          items {
            ... on Skills {
              name
              slug
              image {
                url
              }
            }
                  }
        }
        image {
          title
          description
          contentType
          fileName
          size
          url
          width
          height
        }
      }
    }
  }
  `

  /// Get URL Path
export async function getStaticPaths() { 
  const results = await fetch(`https://graphql.contentful.com/content/v1/spaces/${process.env.NEXT_PUBLIC_CONTENTFUL_SPACE_ID}`, {
    method: "POST",
    headers: {
    "Content-Type": "application/json",
    // Authenticate the request
    Authorization: `Bearer ${process.env.NEXT_PUBLIC_CDA_TOKEN}`,
    },
    // send the GraphQL query
    body: JSON.stringify({
      query: `
        {
          experienceCollection {
            items {
              slug
            }
          }
        }
      `,
    }),
  })
  .then((response) => response.json()); 

  const slugs = results.data.experienceCollection.items.map(experience => experience.slug);

  return {
    paths: slugs.map(slug => ({ params: { slug } })),
    fallback: false,
  }
}

/// GET INFO FROM CONTENTFUL
export async function getStaticProps({ params }) {
    const data = await fetch(`https://graphql.contentful.com/content/v1/spaces/${process.env.NEXT_PUBLIC_CONTENTFUL_SPACE_ID}`, {
        method: "POST",
        headers: {
        "Content-Type": "application/json",
        // Authenticate the request
        Authorization: `Bearer ${process.env.NEXT_PUBLIC_CDA_TOKEN}`,
        },
        // send the GraphQL query
        body: JSON.stringify({ 
          query,
          variables: {
            slug: params.slug,
          },
      }),
    })
    .then((response) => response.json()); 
    return {
        props: {
          results: data,
          params,
        }
    }
}

// Experience Specific Page 
export default function Experience({results, params}) {
    const experience = results.data.experienceCollection.items.find(
      item => item.slug === params.slug
    );
  
    return (
      <>
        <Head>
          <title>{experience.name}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Box 
          sx={{ 
            display: 'flex' 
          }} 
        >
          <Paper 
            elevation={3} 
            sx={{
              m: 5
            }}
          >
            <Box 
              component="main"
              sx={{ 
                display: 'flex', 
                gap: 3,
                flexDirection: 'column',
                flexGrow: 1, p: 3 
                //width: { sm: `calc(100% - ${drawerWidth}px)` } 
              }}
            >
              <Typography variant="h3" align="center">
                {experience.name} 
              </Typography> 

  
              <Box sx={{ 
                  display: 'flex', 
                  justifyContent: 'center' 
                }}
              > 
                <Box
                  component="img"
                  justifyContent="center"
                  sx={{
                    width: 150,
                    maxWidth: { xs: 150, md: 150 },
                  }}
                  alt="Skill Logo"
                  src={experience.image.url}
                />
              </Box>
  
              <Typography 
                paragraph 
                align="center"
                sx= {{
                  px: 4
                }}
              >
                {experience.description}
              </Typography>
            </Box>
          </Paper>
        </Box>
        
      </>
    ) 
  }