import Head from 'next/head'
import * as React from 'react';
import useContentful from '../hooks/use-contenful';
import ExperienceComponent from '../components/experienceComponent';
import Box from '@mui/material/Box';
import Paper from '@mui/material/Paper';
import Typography from '@mui/material/Typography';
import Divider from '@mui/material/Divider';
import Skeleton from '@mui/material/Skeleton';
import Drawer from '../components/drawer'

const drawerWidth = 240;

const query = ` {
  experienceCollection(order: order_ASC) {
    items {
      order
      slug
      name
      position
      location
      dateRange
      url
      linkedin
      experience {
        json
      }
      skillsCollection(limit:10) {
        items {
          ... on Skills {
            name
            slug
            image {
              url
            }
          }
				}
      }
      image {
        title
        description
        contentType
        fileName
        size
        url
        width
        height
      }
    }
  }
}
`

export default function Experience() {
  let {data, errors} = useContentful(query)

  if (errors) {
    return <span style={{color:"red"}}> {errors.map(error => error.message).join(",")} </span>
  }

  if (!data) { 
    return (
      <>
        <Box sx={{
          display: 'flex',
          justifyContent: "center",
          flexWrap: 'wrap',
          width: 'auto',
          mt: 5, 
          mb: 5
          }}
        > 
          <Paper 
            elevation={3} 
            sx={{
              p: 2
            }}
          >
            <Skeleton variant="rounded" width={210} height={210} />
          </Paper>
        </Box> 
      </>
    )
  }
  
  
  return (
      <>
      <Head>
        <title>Experience - Brandon Tetrick</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={{ display: 'flex', justifyContent: 'center' }}>
        <Box
          component="main"
          sx={{ flexGrow: 1, p: 3, width: { sm: `calc(100% - ${drawerWidth}px)`, justifyContent: 'center' } }}
        >
          <Typography 
            variant="h3" 
            align="center"
          >
            Experience
          </Typography>

          <Typography 
            paragraph align="center"
          >
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
            sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
            Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
            Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
            Excepteur sint occaecat cupidatat non proident, 
            sunt in culpa qui officia deserunt mollit anim id est laborum.
          </Typography>

          <Divider/> 

          { data.experienceCollection.items.map(experience => {
            //console.table(experience)
            return <ExperienceComponent experience={experience} key={experience.order} /> 
          })}
        </Box>
      </Box>
      </>
    
  )
}
