import Head from 'next/head'
import * as React from 'react';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import Divider from '@mui/material/Divider';
import Paper from '@mui/material/Paper';
import GetFrontendSkillsAPI from "../lib/frontendSkillsAPI"
import GetBackendSkillsAPI from "../lib/backendSkillsAPI"
import GetDevopsSkillsAPI from "../lib/devopsSkillsAPI"
import GetDesignSkillsAPI from "../lib/designSkillsAPI"
import GetProductivitySkillsAPI from "../lib/productivitySkillsAPI"


const drawerWidth = 240;

export default function Home({allPosts}) {
  return (
      <>
      <Head>
        <title>Home - Brandon Tetrick</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Box sx={{ display: 'flex' }}>
        <Box
          component="main"
          sx={{ flexGrow: 1, p: 3, width: { sm: `calc(100% - ${drawerWidth}px)` } }}
        >
          <Typography 
            variant="h1" 
            align="center"
          >
            Brandon Tetrick
          </Typography>

          <Typography 
            paragraph align="center"
          >
            Former educator turned web developer with 7+ years of working in both the public and private sectors. 
            Has provided academic and professional services for a wide variety of students, clients, and customers. 
            Life-long learner with a passion for web development and digital marketing.
          </Typography>

          <Divider/> 

          <Typography 
            variant="h4" 
            align="center"
            sx= {{
              mt: 5
            }}
          >
            My Skill Set
          </Typography>

          {/* FRONTEND SKILLS BOX  */}
          <GetFrontendSkillsAPI/> 
          
          {/* BACKEND SKILLS BOX  */}
          <GetBackendSkillsAPI/> 

          {/* DEVOPS SKILLS BOX  */}
          <GetDevopsSkillsAPI/> 
          
          {/* DESIGN SKILLS BOX  */}
          <GetDesignSkillsAPI/>  

          {/* PRODUCTIVITY SKILLS BOX  */}
          <GetProductivitySkillsAPI/> 
        </Box>
      </Box>  
      </>
  )
}
