import Head from 'next/head'
import * as React from 'react';

// Material UI
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import Divider from '@mui/material/Divider';

//Components
import SkillsBox from '../components/skills/skillsBox.js';
import SkeletonLoading from '../components/skeletonLoading.js';

//Hooks
import useContentful from '../hooks/use-contenful';

const query = ` {
  skillsCollection {
    items {
      slug
      name
      usage
      image {
        url
      }
    }
  }
}
`

const drawerWidth = 240;

export default function Home() {
  
  let {data, errors} = useContentful(query)

  if (errors) {
    return <span style={{color:"red"}}> {errors.map(error => error.message).join(",")} </span>
  }

  //Skeleton
  if (!data) { 
    return <SkeletonLoading />;
  }

  return (
      <>
      <Head>
        <title>Home - Brandon Tetrick</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Box sx={{ display: 'flex' }}>
        <Box
          component="main"
          sx={{ flexGrow: 1, p: 3, width: { sm: `calc(100% - ${drawerWidth}px)` } }}
        >
          <Typography 
            variant="h1" 
            align="center"
          >
            Brandon Tetrick
          </Typography>

          <Typography 
            paragraph align="center"
          >
            Results-driven web developer with over 7 years of experience spanning diverse projects in both public and private sectors. 
            Specializing in developing dynamic websites that blend creativity and cutting-edge technology. 
            Adept at implementing strategic digital marketing initiatives that have led to a 25% average increase in website traffic across various projects. 
            Lifelong learner, dedicated to staying ahead of industry trends and leveraging emerging technologies. 
            Passionate about web development and digital innovation. Proficient in HTML, CSS, JavaScript, and proficient in collaborating with cross-functional teams to deliver high-quality solutions.
          </Typography>
          
          <Divider/> 

          <Typography 
            variant="h4" 
            align="center"
            sx= {{
              mt: 5
            }}
          >
            My Skill Set
          </Typography>

          <SkillsBox data={data} />
        </Box>
      </Box>  
      </>
  )
}
