import Head from 'next/head'
import * as React from 'react';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';

import GetSkills from "../lib/skillsHomeAPI"


const drawerWidth = 240;

export default function Home({allPosts}) {
  return (
      <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ display: 'flex' }}>
        <Box
          component="main"
          sx={{ flexGrow: 1, p: 3, width: { sm: `calc(100% - ${drawerWidth}px)` } }}
        >
          <Typography variant="h1" align="center">
          Brandon Tetrick
          </Typography>
          <Typography paragraph align="center">
          Former educator turned web developer with 7+ years of working in both the public and private sectors. 
          Has provided academic and professional services for a wide variety of students, clients, and customers. 
          Life-long learner with a passion for web development and digital marketing.
          </Typography>
          <GetSkills/> 
        </Box>
      </Box> 
      </>
  )
}
